language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py26
sudo: false
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  webhooks: https://hook.bearychat.com/=bw6L5/travis/4e45e595fd0badd5029a4d680bf71e72
